# pyproject.toml

[build-system]
requires = [
  "setuptools>=68",
  "wheel",
  "setuptools_scm>=8",
]
build-backend = "setuptools.build_meta"

[project]
name = "cars_point_cloud_to_mesh"
description = "Mesh generation from CARS point clouds"
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.10"

dynamic = ["version"]

license = "Apache-2.0"
license-files = ["LICENCE", "NOTICE", "AUTHORS.md"]

authors = [
  { name = "CS Group", email = "ospo@cs-soprasteria.com" },
]

keywords = [
  "cars",
  "cars_point_cloud_to_mesh",
  "DEM",
  "pandora",
  "photogrammetry",
  "3D",
]

classifiers = [
  "Development Status :: 4 - Beta",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "Intended Audience :: End Users/Desktop",
  "Intended Audience :: Science/Research",
  "Natural Language :: English",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Topic :: Software Development :: Libraries :: Python Modules",
]

dependencies = [
  "argparse",
  "cars==1.0.0",
  "json-checker",
  "numba",
  "numpy",
  "rasterio",
  "scipy",
  "triangle>=20230923",
]

[project.urls]
Homepage = "https://github.com/CS-SI/cars_point_cloud_to_mesh"

[project.scripts]
cars_point_cloud_to_mesh = "cars_point_cloud_to_mesh.cli:main"

[project.entry-points."cars.plugins"]
plugin = "cars_point_cloud_to_mesh"

[project.optional-dependencies]
dev = [
  "build",
  "black>=21.5b0",
  "flake8>=3.9.1",
  "flake8-bugbear>=21.4.3",
  "flake8-comprehensions>=3.4.0",
  "isort>=5.8.0",
  "pre-commit",
  "pylint",
  "pytest",
  "pytest-cov",
  "twine",
  "setuptools_scm",
]

docs = [
  "sphinx",
  "sphinx_autoapi",
  "sphinx_rtd_theme",
  "sphinx_tabs",
]

notebook = [
  "bokeh",
  "notebook",
]


[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["cars_point_cloud_to_mesh*"]

[tool.setuptools.package-data]
cars_point_cloud_to_mesh = ["data/*"]

[tool.setuptools_scm]
# version_scheme = "no-guess-dev"
# local_scheme = "node-and-date"


[tool.black]
line-length = 80
exclude = """
/(
  \\.eggs
| \\.git
| \\.mypy_cache
| \\.nox
| \\.tox
| _build
| build
| dist
| venv
)/
"""

[tool.isort]
profile = "black"
line_length = 80

[tool.mypy]
no_implicit_optional = false
strict_optional = false
allow_redefinition = true
allow_untyped_globals = true
local_partial_types = false
warn_unused_ignores = true
check_untyped_defs = true
ignore_missing_imports = true
disable_error_code = "attr-defined"

[[tool.mypy.overrides]]
module = ["setuptools"]
ignore_missing_imports = true
